#!/bin/bash

googleimagesdownload -l 1000 -s medium -kf keywords.txt -cd ./chromedriver

mkdir hotdog
mv downloads/hotdog hotdog
cp -av downloads test
cp -av downloads train
./prune test
./prune train
./resize
