#!/bin/bash

if [ "$1" == "test" ]; then
	echo pruning test set
	cd test
	for dir in `ls -d *`
	do
		cd $dir
		\rm -rf [123456789].*.jpg
		\rm -rf [12345678]?.*.jpg
		\rm -rf [123456789].*.jpeg
		\rm -rf [12345678]?.*.jpeg
		\rm -rf [123456789].*.png
		\rm -rf [12345678]?.*.png
		cd ..
	done
elif [ "$1" == "train" ]; then
	echo pruning training set
	cd train
	for dir in `ls -d *`
	do
		cd $dir
		\rm -rf [9]?.*.jpg
		\rm -rf 100.*.jpg
		\rm -rf [9]?.*.jpeg
		\rm -rf 100.*.jpeg
		\rm -rf [9]?.*.png
		\rm -rf 100.*.png
		cd ..
	done
else
	echo "usage: $0 [test | train]"
fi
